version: '3'

services:
  nodeapp:
    image: squishyu/bun-alpine
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}-app
    working_dir: /app
    volumes:
      - ./project/${CODE_PATH}:/app
    ports:
      - ${NODE_PORT}:${NODE_PORT_EXPOSE:-3000}  # Provide a default value of 3000 if NODE_PORT_EXPOSE is not set

    # Command to run during the build process
    command: sh -c "${NODE_START}"

    # Other options you might need
    environment:
      - NODE_ENV=dev
