# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Install dependencies
# RUN npm install

# Build the application
# RUN npm run build

# Expose the port that Nuxt.js will run on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
